### ISSUE TITLE
Colab issue 

### ISSUE THREAD

**Issue by MONICA-PALLA** [TuragaLab/flyvis#3]
Hi, 

Was trying to run the colab shared in the Readme of this project.

Encountered following issue, was wondering if anyone here could help me to proceed without such encounters.

![Screenshot from 2024-10-17 01-03-49](https://github.com/user-attachments/assets/18847023-edb6-4c29-b473-8cd48f03d559)

Thanks in advance!
Mounica.

**Comment by miro-ka** [comment]
Hi Mounica, 
New to flyvis, but looking at the code animations should be under analysis. Can you try with:

flyvision.**analysis**.animations.imshow

or alternatively (looking at [example](https://github.com/TuragaLab/flyvis/blob/28b6e0fb36edd3f3d2e49f8ee7d17b5d7fc63ba6/docs/docs/examples/07_flyvision_providing_custom_stimuli.md?plain=1#L45): 

```
from flyvision.analysis import animations
animation = animations.Imshow(sequences, cmap=plt.cm.binary_r)
```
Hope this helps,
/m

**Comment by MONICA-PALLA** [comment]
Hi Miro,

from flyvision.analysis import animations
animation = animations.Imshow(sequences, cmap=plt.cm.binary_r)

This worked!!

Thanks a lot!!
Mounica.
