### ISSUE TITLE
FileExistsError when creating network directory during training

### ISSUE THREAD

**Issue by L-in-da** [TuragaLab/flyvis#4]
#### Issue Summary
When creating a network directory in the `solver.py` a `FileExisitsError` is raised although the network is created for the first time.

#### Steps to Reproduce
The error is raised by line 109 in solver.py:

``` 
self.dir = NetworkDir(
            name, {**(config or {}), **dict(delete_if_exists=delete_if_exists)}
        ) 
``` 

Minimal example to reproduce the error:
```
from pathlib import Path

network_dir = Path('task/0000/000')

if not network_dir.exists():  
            network_dir.mkdir(parents=True)

from flyvision.network import NetworkDir
dir = NetworkDir(network_dir, **{"connectome":[1]})  
```

#### Expected Behavior
For every network, a directory should be created

#### Observed Behavior
Error message: `FileExistsError: path (incompatible config): {'passed: Namespace(type='NetworkdDir', connectome=[1]), 'stored': None}

#### Suggested Fixes or Ideas
 Either create dir of parent folder in compute_cloud_utils.py:
```
network_dir = Path('task/0001/000')

if not network_dir.parent.exists():
            network_dir.parent.mkdir(parents=True)

from flyvision.network import NetworkDir
wrap = NetworkDir(network_dir, **{"connectome":[1]})
```
or fix the issue in datamate

**Comment by lappalainenj** [comment]
Thanks! This is a bug in flyvis and the correct behavior of datamate.

Your proposed fix is correct. The intention is to create the ensemble directory (`network_dir.parent`) already in `compute_cloud_utils.py` to be able to write log files to it. This was likely introduced during refactoring or by changing the default config. Could you make a PR with a fix?

In the meantime, the workaround from the command line is to add `delete_if_exists=true` as an argument. 
Within a python workflow one can also disable the strict config matching, like this

```python
# At the beginning of your workflow
import datamate
datamate.enforce_config_match(False)

(Rest of you workflow ...)
```
